function [objFcn] = objFcnLSTM(p, t, pv, tv, inputName)
    objFcn = @valErrorFcn;
    function [valError, cons, fileName] = valErrorFcn(optVars)  
        nFeatures = size(p{1}, 1);

        layers = [
               sequenceInputLayer(nFeatures)
               lstmLayer(optVars.NumHiddenUnits, OutputMode="last")
               fullyConnectedLayer(ESPConst.N_OUTPUT_CLASSES_ALL)
               softmaxLayer
               classificationLayer
                 ];
        validationFrequency = floor(numel(t) / optVars.MiniBatchSize);
        fileName = "LSTM" + ...
                   "NHiddenUnits" + optVars.NumHiddenUnits + ...
                   "Patient" + replace(inputName, ESPConst.EXTENSION_DATA, "");

        options = trainingOptions(string(optVars.Solver), ...
            'InitialLearnRate', optVars.InitialLearnRate, ...
            'MaxEpochs', optVars.MaxEpochs, ... 
            'SequencePaddingDirection', "left", ...
            'Shuffle', "never", ...
            'LearnRateSchedule', 'piecewise', ...
            'LearnRateDropPeriod', round(optVars.MaxEpochs / 3), ...
            'LearnRateDropFactor', optVars.LearnRateDropFactor, ...
            'MiniBatchSize', optVars.MiniBatchSize, ...
            'L2Regularization', optVars.L2Regularization, ...
            'ExecutionEnvironment', "gpu", ...
            'Verbose', true, ...
            'Plots', 'training-progress', ...
            'ValidationFrequency', validationFrequency);

        if optVars.Solver == "sgdm"
            options.Momentum = optVars.Momentum;
        end

        tNN = trainNetwork(p, t, layers, options);
        predicted = classify(tNN, pv);
        valError =  1 - mean(predicted == transpose(tv));
        fileName = "Err" + num2str(valError) + fileName + ESPConst.EXTENSION_DATA;
        save(ESPConst.PATH_LSTMS + fileName, ...
            'tNN', ...
            'valError', ...
            'options');
        cons = [];
    end
end